# Generated by Django 3.1.7 on 2021-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
