# Generated by Django 3.1.7 on 2021-05-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability',
            field=models.CharField(choices=[('A', 'Growl'), ('B', 'Take Down'), ('C', 'Tackle'), ('D', 'Rest'), ('E', 'Protect'), ('F', 'Special Attack')], default='A', max_length=1),
        ),
    ]
