# Generated by Django 3.1.7 on 2021-05-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210517_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['name']},
        ),
    ]
