# Generated by Django 3.1.7 on 2021-05-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210521_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='photo',
            new_name='image',
        ),
    ]
